package:
  name: libxcrypt-devel-el8-x86_64
  version: 4.1.1

source:
  - url: https://download.rockylinux.org/vault/rocky/8.9/BaseOS/x86_64/os/Packages/l/libxcrypt-devel-4.1.1-6.el8.x86_64.rpm
    sha256: 71242b7ce34cbadc0eb117e4608887ddd64236e7e808fb593f9b3d7cccdcbc40
    no_hoist: true
    folder: binary
  # - url: https://download.rockylinux.org/vault/rocky/8.9/BaseOS/source/tree/Packages/l/libxcrypt-4.1.1-6.el8.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  number: 0
  noarch: generic
  binary_relocation: false
  detect_binary_files_with_prefix: false
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - libxcrypt-el8-x86_64 ==4.1.1 *_0
  host:
    - libxcrypt-el8-x86_64 ==4.1.1 *_0
    - sysroot_linux-64 2.28.*
  run:
    - libxcrypt-el8-x86_64 ==4.1.1 *_0
    - sysroot_linux-64 2.28.*
test:
  commands:
    - echo "it installs!"

about:
  home: https://github.com/besser82/libxcrypt
  license: LGPL-2.0-or-later AND BSD AND Public Domain
  license_family: LGPL
#  license_file: libxcrypt-copying.lib
  summary: (CDT) Development files for libxcrypt
  description: |
    The libxcrypt-devel package contains libraries and header files for
    developing applications that use libxcrypt.
extra:
  recipe-maintainers:
    - conda-forge/help-cdts

