package:
  name: kmod-libs-el8-x86_64
  version: 25

source:
  - url: https://download.rockylinux.org/vault/rocky/8.9/BaseOS/x86_64/os/Packages/k/kmod-libs-25-19.el8.x86_64.rpm
    sha256: b89b400448003842e40d7252320ed56d1750d52ae846ac04090169e38fb0f654
    no_hoist: true
    folder: binary
  # - url: https://download.rockylinux.org/vault/rocky/8.9/BaseOS/source/tree/Packages/k/kmod-25-19.el8.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  skip: True  # [not (linux and x86_64)]
  number: 0
  noarch: generic
  binary_relocation: false
  detect_binary_files_with_prefix: false
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - sysroot_linux-64 2.28.*
  host:
  run:
    - sysroot_linux-64 2.28.*
    - libgcc-ng
    - libxcrypt-el8-x86_64 >=4.1.1 *_0
    - openssl 1  # libcrypto.so.1.1
    - xz
    - zlib

test:
  commands:
    - test -f ${PREFIX}/x86_64-conda_el8-linux-gnu/sysroot/usr/lib64/libkmod.so.2
    - test -f ${PREFIX}/x86_64-conda_el8-linux-gnu/sysroot/usr/lib64/libkmod.so.2.3.3

about:
  home: http://git.kernel.org/?p=utils/kernel/kmod/kmod.git;a=summary
  license: LGPL-2.1-only  # LGPLv2+
  license_family: LGPL
  license_file:
    - COPYING
  summary: (CDT) Libraries to handle kernel module loading and unloading
  description: |
    The kmod-libs package provides runtime libraries for any application that
    wishes to load or unload Linux kernel modules from the running system.
extra:
  recipe-maintainers:
    - conda-forge/help-cdts
