package:
  name: libselinux-devel-el8-x86_64
  version: 2.9

source:
  - url: https://download.rockylinux.org/vault/rocky/8.9/BaseOS/x86_64/os/Packages/l/libselinux-devel-2.9-8.el8.x86_64.rpm
    sha256: e51c71849563d4fc041aee519b0771f71188f1b4f3d29f44b102919334059ea4
    no_hoist: true
    folder: binary
  # - url: https://download.rockylinux.org/vault/rocky/8.9/BaseOS/source/tree/Packages/l/libselinux-2.9-8.el8.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  skip: True  # [not (linux and x86_64)]
  number: 0
  noarch: generic
  binary_relocation: false
  detect_binary_files_with_prefix: false

requirements:
  host:
  run:
    - sysroot_linux-64 2.28.*
    - libselinux-el8-x86_64 ==2.9 *_0
    - libsepol-devel-el8-x86_64 >=2.9 *_0

test:
  requires:
    - pkg-config
  commands:
    - test -f ${PREFIX}/x86_64-conda_el8-linux-gnu/sysroot/usr/include/selinux/selinux.h
    - test -f ${PREFIX}/x86_64-conda_el8-linux-gnu/sysroot/usr/lib64/libselinux.so
    - export PKG_CONFIG_PATH=${PREFIX}/x86_64-conda_el8-linux-gnu/sysroot/usr/lib64/pkgconfig
    - pkg-config --cflags libselinux

about:
  home: https://github.com/SELinuxProject/selinux/wiki
  license: Public-Domain
  license_family: Public-Domain
  summary: (CDT) Header files and libraries used to build SELinux
  description: |
    The libselinux-devel package contains the libraries and header files needed
    for developing SELinux applications.
extra:
  recipe-maintainers:
    - conda-forge/help-cdts
