package:
  name: libsepol-devel-el8-x86_64
  version: 2.9

source:
  - url: https://download.rockylinux.org/vault/rocky/8.9/BaseOS/x86_64/os/Packages/l/libsepol-devel-2.9-3.el8.x86_64.rpm
    sha256: 400722a407b15af596c530a7d7f83c429e2577337e56ca93c711ad94ca6155e6
    no_hoist: true
    folder: binary
  # - url: https://download.rockylinux.org/vault/rocky/8.9/BaseOS/source/tree/Packages/l/libsepol-2.9-3.el8.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  skip: True  # [not (linux and x86_64)]
  number: 0
  noarch: generic
  binary_relocation: false
  detect_binary_files_with_prefix: false

requirements:
  host:
  run:
    - sysroot_linux-64 2.28.*
    - libsepol-el8-x86_64 ==2.9 *_0

test:
  requires:
    - pkg-config
  commands:
    - test -f ${PREFIX}/x86_64-conda_el8-linux-gnu/sysroot/usr/include/sepol/sepol.h
    - test -f ${PREFIX}/x86_64-conda_el8-linux-gnu/sysroot/usr/lib64/libsepol.so
    - export PKG_CONFIG_PATH=${PREFIX}/x86_64-conda_el8-linux-gnu/sysroot/usr/lib64/pkgconfig
    - pkg-config --cflags libsepol

about:
  home: https://github.com/SELinuxProject/selinux/wiki
  license: LGPL-2.0-or-later
  license_family: LGPL
#  license_file: libsepol-license
  summary: (CDT) Header files and libraries used to build policy manipulation tools
  description: |
    The libsepol-devel package contains the libraries and header files needed for
    developing applications that manipulate binary policies.
extra:
  recipe-maintainers:
    - conda-forge/help-cdts
