package:
  name: libcap-ng-devel-el8-x86_64
  version: 0.7.11

source:
  - url: https://download.rockylinux.org/vault/rocky/8.9/BaseOS/x86_64/os/Packages/l/libcap-ng-devel-0.7.11-1.el8.x86_64.rpm
    sha256: 9351a96d4320814185fb5336a2fe41bfd676f655acdf3aa070c964dd8e74acd0
    no_hoist: true
    folder: binary
  # - url: https://download.rockylinux.org/vault/rocky/8.9/BaseOS/source/tree/Packages/l/libcap-ng-0.7.11-1.el8.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  skip: True  # [not (linux and x86_64)]
  number: 0
  noarch: generic
  binary_relocation: false
  detect_binary_files_with_prefix: false

requirements:
  host:
  run:
    - sysroot_linux-64 2.28.*
    - libcap-ng-el8-x86_64 ==0.7.11 *_0

test:
  commands:
    - test -f ${PREFIX}/x86_64-conda_el8-linux-gnu/sysroot/usr/include/cap-ng.h
    - test -f ${PREFIX}/x86_64-conda_el8-linux-gnu/sysroot/usr/lib64/libcap-ng.so

about:
  home: http://people.redhat.com/sgrubb/libcap-ng
  license: LGPL-2.1-only  # LGPLv2+
  license_family: LGPL
  license_file:
    - COPYING.LIB
  summary: (CDT) Header files for libcap-ng library
  description: |
    The libcap-ng-devel package contains the files needed for developing
    applications that need to use the libcap-ng library.
extra:
  recipe-maintainers:
    - conda-forge/help-cdts
