package:
  name: kmod-el8-x86_64
  version: 25

source:
  - url: https://download.rockylinux.org/vault/rocky/8.9/BaseOS/x86_64/os/Packages/k/kmod-25-19.el8.x86_64.rpm
    sha256: 993d53503b870d0520f04183c8642ba2435fbd78d0dd44fbae4b1d3c05416ef1
    no_hoist: true
    folder: binary
  # - url: https://download.rockylinux.org/vault/rocky/8.9/BaseOS/source/tree/Packages/k/kmod-25-19.el8.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  skip: True  # [not (linux and x86_64)]
  number: 0
  noarch: generic
  binary_relocation: false
  detect_binary_files_with_prefix: false
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - sysroot_linux-64 2.28.*
  host:
  run:
    - sysroot_linux-64 2.28.*
    - kmod-libs-el8-x86_64 ==25 *_0
    - libgcc-ng
    - libxcrypt-el8-x86_64 >=4.1.1 *_0
    - xz
    - zlib

test:
  commands:
    - test -f ${PREFIX}/x86_64-conda_el8-linux-gnu/sysroot/usr/sbin/modinfo

about:
  home: http://git.kernel.org/?p=utils/kernel/kmod/kmod.git;a=summary
  license: GPL-2.0-or-later
  license_family: GPL2
#  license_file: kmod-copying
  summary: (CDT) Linux kernel module management utilities
  description: |
    The kmod package provides various programs needed for automatic loading and
    unloading of modules under 2.6, 3.x, and later kernels, as well as other
    module management programs. Device drivers and filesystems are two examples of
    loaded and unloaded modules.
extra:
  recipe-maintainers:
    - conda-forge/help-cdts
