package:
  name: audit-libs-el8-x86_64
  version: 3.0.7

source:
  - url: https://download.rockylinux.org/vault/rocky/8.9/BaseOS/x86_64/os/Packages/a/audit-libs-3.0.7-5.el8.x86_64.rpm
    sha256: fd745f486bd742b474ceef449fcdf4398d4406675a1c60de8b79ed8d5bdf40e4
    no_hoist: true
    folder: binary
  # - url: https://download.rockylinux.org/vault/rocky/8.9/BaseOS/source/tree/Packages/a/audit-3.0.7-5.el8.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  skip: True  # [not (linux and x86_64)]
  number: 0
  noarch: generic
  binary_relocation: false
  detect_binary_files_with_prefix: false
  ignore_run_exports:
    - sysroot_linux-64
    - libcap-ng-el8-x86_64
  missing_dso_whitelist:
    - '*'

requirements:
  host:
    - sysroot_linux-64 2.28.*
    - libcap-ng-el8-x86_64 >=0.7.11 *_0
  run:
    - sysroot_linux-64 2.28.*
    - libcap-ng-el8-x86_64 >=0.7.11 *_0

test:
  commands:
    - echo "it installs!"

about:
  home: http://people.redhat.com/sgrubb/audit/
  license: LGPL-2.0-or-later
  license_family: LGPL
#  license_file: audit-libs-copying.lib
  summary: (CDT) Dynamic library for libaudit
  description: |
    The audit-libs package contains the dynamic libraries needed for applications
    to use the audit framework.
extra:
  recipe-maintainers:
    - conda-forge/help-cdts

